/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 751a7ef0204e37564547937fa13c0dba)
declare namespace Cloudflare {
  interface Env {
    DB: D1Database
  }
}
interface Env extends Cloudflare.Env {}
