/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 0390eddb221c0ee793de780610f80bc7)
declare namespace Cloudflare {
	interface Env {
		VALUE_FROM_CLOUDFLARE: "Hello from Cloudflare";
		API: Fetcher;
	}
}
interface Env extends Cloudflare.Env {}
